version: '3'

services:
  api:
    image: api-example-api
    container_name: api-example-api
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
    depends_on:
      - api-example-db-dev
      - api-example-db-integration-test

  api-example-db-dev:
    image: postgres:15.3
    container_name: api-example-db-dev
    restart: unless-stopped
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    volumes:
      - api-example-db-dev:/data/postgres
    ports:
      - '5432:5432'

  api-example-db-integration-test:
    image: postgres:15.3
    container_name: api-example-db-integration-test
    restart: unless-stopped
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      PGDATA: /data/postgres
    ports:
      - '5433:5432'

volumes:
  api-example-db-dev:
